import Feed from "./components/Feed/Feed";
import Modal from "./components/Modal/Modal";
import SideBar from "./components/SideBar/SideBar";
import Widgets from "./components/Widgets/Widgets";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen max-w-7xl mx-auto ">
          {/* side bar */}
          <SideBar />
          {/* feed */}
          <Feed />
          {/* widgets */}
          <Widgets />
          {/* Modal */}
          {/* <Modal /> */}
        </main>
        {children}
      </body>
    </html>
  );
}
